server:
  port: 28080
#??Mybatis????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 8
        min-idle: 1
mybatis-plus:
  configuration:
    # ??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml